### ISSUE TITLE
Should be saving new entries as version 5

### ISSUE THREAD

**Issue by chadfawcett** [tickbin/entry-parser#12]
Since https://github.com/tickbin/entry-parser/commit/4ab04ca367410d1cefc7dedac209158dbd673ec2 , we should be saving the entries as version 5. Currently since they are being saved as version 4, they are being run though the upgrader for 4 to 5 which takes the start and end values and regenerates the startArr and endArr values in UTC.

**Comment by jonotron** [comment]
This repository doesn't seem to concern itself with the Entry document itself, merely parsing strings into components to be passed into a new Entry. The Entry object model should be the thing specifying v5, not this parser. Unless I am not fully understanding.

**Comment by chadfawcett** [comment]
This code, as extracted from tickbin/tickbin included adding a version to the parsed object. https://github.com/tickbin/entry-parser/blob/master/src/index.js#L7 This module does create the whole entry document. It replaces the `new Entry` module that used to be in tickbin.

**Comment by jonotron** [comment]
Gotcha, I missed that. Then we may have to bring the upgrade mappers into
this repo. It feels strange that the entry document is here but the upgrade
logic is elsewhere.

**Comment by chadfawcett** [comment]
I agree it is a little weird. Created #13
